nelmio_api_doc:
    documentation:
        info:
            title: Bilemo
            description: Manage your users & products using our API
            version: 1.0.0
        tags:
          - name: "User"
            description: "Users Request"
          - name: "Product"
            description: "Products Request"
          - name: "Client"
            description: "Client Registration"
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT


    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
